export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS='SET_INGREDIENTS';

export const PURCHASE_BURGER_START='PURCHASE_BURGER_START';
export const PURCHASE_SUCESS='PURCHASE_BURGER_SUCESS';
export const PURCHASE_BURGER_FAIL='PURCHASE_BURGER_FAIL';